Translated Description
CheckIO-to-German/Multiplication-Table pull request #2
Opened 2016-10-09 19:59 UTC by DahliaSR

2016-10-10 05:48 UTC, GiForce requested changes
Don't blame Stephan ;)

2016-10-10 05:48 UTC, GiForce commented on translations/de/info/task_description.html
> +    Nach der Lektüre von "Alice im Wunderland ", haben sich unsere Roboter entschieden,
Are both commas here necessary? It's so bumby 🐫I'd dare to go with none. Even the original should at least take the comma out the quotation marks.

2016-10-10 05:48 UTC, GiForce commented on translations/de/info/task_description.html
> +    ihr eigenes Einmaleins zu erstellen. Stephan wollte diese Mission leiten
He probably didn't want to. would is the past tense of will.

2016-10-10 05:48 UTC, GiForce commented on translations/de/info/task_description.html
> +    Es ist eine ziemlich seltsame Methode, wenn wir so direkt sein wollen.
I would change that last sentence.
Just "Eine ziemlich seltsame Methode, wenn wir ehrlich sein wollen.." sounds better
or even "Eine ziemlich seltsame Methode, unverblümt( od freiheraus, od ehrlich) gesagt"

2016-10-10 05:48 UTC, GiForce commented on translations/de/info/task_description.html
> +    anwenden kann.
we say eine Funktion _führt aus_,  rather than _wendet an_, dh: _..die diese Art von  "Multiplikation" ausführen kann_

2016-10-10 05:48 UTC, GiForce commented on translations/de/info/task_description.html
> +    Informatik - rum.<br>
That ending, please not. End after Informatik. That's so to emphasize, you could even have an exclamation mark there.

2016-10-10 05:48 UTC, GiForce commented on translations/de/info/task_short_description.html
> +Es gibt allerdings ein kleines Problem: Stephan vergessen, wie man multipliziert...
"E. T. nach Hause telefonieren".  ;)

2016-10-10 05:48 UTC, GiForce commented on translations/de/info/task_description.html
> +    sodass wir am Ende drei Tabellen haben.
Your describtion of the notation is unclear and actually wrong.

> Damit füllen wir je....

We don't fill the table with the previous mentioned vertic- and horizontally written numbers. The results of the binary operations between the column values (horizontally number) and the row values fill these tables. Like the original states, where they cross each other tablewise.

2016-10-10 18:26 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Nach der Lektüre von "Alice im Wunderland ", haben sich unsere Roboter entschieden,
The firt one is wrong, the second is optional...
Let's get rid of them.

2016-10-10 18:29 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    ihr eigenes Einmaleins zu erstellen. Stephan wollte diese Mission leiten
Yea, BUT Bryukh is the author of the task!
And it matches the context.

2016-10-10 18:57 UTC, DahliaSR commented on translations/de/info/task_short_description.html
> +Es gibt allerdings ein kleines Problem: Stephan vergessen, wie man multipliziert...
"Wie multiplizieren man, vergessen Stephan hat" - Meister Yodaß!?! :sunglasses:

2016-10-10 20:13 UTC, GiForce commented on translations/de/info/task_description.html
> +    ihr eigenes Einmaleins zu erstellen. Stephan wollte diese Mission leiten
maybe a missunderstanding? 🐙 _would lead this mission_ wie Bryukh es formuliert, heisst nicht _wollte diese Mission leiten_ sondern _sollte diese Mission leiten_  oder _hätte ..sollen_. would != wollen. 
_Würde_ könnte man auch übersetzen, passt aber weniger.

2016-10-10 20:35 UTC, GiForce commented
Yes, yes, Yoda and E.T., buddies they are 

> Am 10.10.2016 um 20:57 schrieb DahliaSR <notifications@github.com>:
> 
> @DahliaSR commented on this pull request.
> 
> In translations/de/info/task_short_description.html <https://github.com/CheckIO-to-German/Multiplication-Table/pull/2>:
> 
> > \ No newline at end of file
> +"Alice im Wunderland" hat unsere Roboter inspiriert ihr eigenes Einmaleins zu erstellen.<br>
> +Es gibt allerdings ein kleines Problem: Stephan vergessen, wie man multipliziert...
> "Wie multiplizieren man, vergessen Stephan hat" - Meister Yodaß!?! 😎
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/CheckIO-to-German/Multiplication-Table/pull/2>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ARBj_YiZXOHQvc3OpaCc_g9ew1qw3nebks5qyoqggaJpZM4KSF-0>.
>

2016-10-11 20:34 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    ihr eigenes Einmaleins zu erstellen. Stephan wollte diese Mission leiten
_would lead this mission_ and _was a bad idea_
**was** ist Vergangenheit, man kann also annehmen das Stephan die Leitung bereits übernommen hat. Schliesslich besteht die Aufgabe ja darin Stephans Variante umzusetzten,
was wohl nicht nötig wäre, wenn Stephan nicht zuständig ist.

Der Kontext ist leider nicht ganz klar, was vermutlich daran liegt, dass Englisch nicht die Muttersprache von Bryukh ist. Solche Unstimmigkeiten sind mir bei seinen Aufgaben schon öfter aufgefallen. Hier ist es also an uns beiden eine brauchbare Lösung zu finden.

Wir können, denke ich, zwei Wege gehen:  
- Stephan _hat_ die Leitung übernommen **und** es _war_ ein schlechte Idee
**oder**
- Stephan _möchte_ die Leitung übernommen **und** es _ist_ eine schlechte Idee

Also ICH tendiere ja zu ersterem... :stuck_out_tongue_winking_eye:

2016-10-12 02:59 UTC, GiForce commented
On track, we agree on the narrative tense!
Dachte, wenn es etwa heisst  „Stephan sollte diese Mission leiten (yeah, das war wahrscheinlich keine gute Idee)“ , dann bedeutet das,  Er leitete die Mission – bis er mit seiner komischen Methode daherkommt, und deswegen dann der geehrte checkIO - Coder ranmuss, also die Mission übernehmen (leiten) muss.
Aber vielleicht dieser Art: „Stephan hätte diese Mission leiten sollen. Aber das war vielleicht keine so gute Idee, denn er vergass wie man multipliziert und erfand dafür eine eigene Methode. Und die ist eher seltsam, wenn wir ehrlich sind"

> Am 11.10.2016 um 22:34 schrieb DahliaSR <notifications@github.com>:
> 
> @DahliaSR commented on this pull request.
> 
> In translations/de/info/task_description.html <https://github.com/CheckIO-to-German/Multiplication-Table/pull/2>:
> 
> >      </p>
>  
>      <p style="clear: both;"></p>
>  
>  </div>
>  
>  <p>
> -    After reading "Alice's Adventures in Wonderland,"
> -    our robots decided to create their own "Multiplication table."
> -    Stephan would lead this mission (yeah, that probably was a bad idea).
> -    He forgot how to do multiplication and tried to invent a new method.
> -    It’s a rather strange method if we may be so blunt.
> +    Nach der Lektüre von "Alice im Wunderland ", haben sich unsere Roboter entschieden,
> +    ihr eigenes Einmaleins zu erstellen. Stephan wollte diese Mission leiten
> would lead this mission and was a bad idea
> was ist Vergangenheit, man kann also annehmen das Stephan die Leitung bereits übernommen hat. Schliesslich besteht die Aufgabe ja darin Stephans Variante umzusetzten,
> was wohl nicht nötig wäre, wenn Stephan nicht zuständig ist.
> 
> Der Kontext ist leider nicht ganz klar, was vermutlich daran liegt, dass Englisch nicht die Muttersprache von Bryukh ist. Solche Unstimmigkeiten sind mir bei seinen Aufgaben schon öfter aufgefallen. Hier ist es also an uns beiden eine brauchbare Lösung zu finden.
> 
> Wir können, denke ich, zwei Wege gehen:
> 
> Stephan hat die Leitung übernommen und es war ein schlechte Idee oder
> Stephan möchte die Leitung übernommen und es ist eine schlechte Idee
> Also ICH tendiere ja zu ersterem... 😜
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/CheckIO-to-German/Multiplication-Table/pull/2>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ARBj_fzwA2EsPhJ0ZljrsKfoyfi8PIOCks5qy_LAgaJpZM4KSF-0>.
>

2016-10-12 19:23 UTC, DahliaSR commented
> Aber vielleicht dieser Art: „Stephan hätte diese Mission leiten sollen. Aber das war vielleicht keine so gute Idee, denn er vergass wie man multipliziert und erfand dafür eine eigene Methode. Und die ist eher seltsam, wenn wir ehrlich sind"

Das ist Super... naja fast!
- _Aber das war vielleicht keine_ ==> _Das war vermutlich keine_ **oder** _Das war keine_
- _denn er vergass wie man_ ==> klingt nach Märchenstunde _denn er hat vergessen wie man_

Passt das so?

2016-10-12 21:35 UTC, GiForce commented
🤖💬✅
> On 12 Oct 2016, at 21:23, DahliaSR <notifications@github.com> wrote:
> 
> Aber vielleicht dieser Art: „Stephan hätte diese Mission leiten sollen. Aber das war vielleicht keine so gute Idee, denn er vergass wie man multipliziert und erfand dafür eine eigene Methode. Und die ist eher seltsam, wenn wir ehrlich sind"
> 
> Das ist Super... naja fast!
> 
> Aber das war vielleicht keine ==> Das war vermutlich keine oder Das war keine
> denn er vergass wie man ==> klingt nach Märchenstunde denn er hat vergessen wie man
> Passt das so?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-10-13 19:27 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    ihr eigenes Einmaleins zu erstellen. Stephan wollte diese Mission leiten
:white_check_mark:

2016-10-15 16:53 UTC, GiForce approved these changes
🎃

2016-10-15 18:49 UTC, DarkoRevan approved these changes

2016-10-15 18:53 UTC, DarkoRevan approved these changes
Nice!

2016-10-16 17:55 UTC, merged